export const DEFAULT_VALUE = {
  givenNames: 'Joe',
  surname: 'Consumer',
  email: 'test@scalapay.com',
  phoneNumber: '0400000001',
  sku: '12341234',
  category: 'clothes',
  nameItem: 'T-Shirt',
  quantity: 1,
  price: '10',
  subcategory: ['short', 'shirt'],
  pageUrl: 'https://www.scalapay.com//product/view/',
  imageUrl: 'https://www.scalapay.com//product/view/',
  gtin: '123458791330',
  countryCode: 'IT',
  postcode: '50056',
  nameShipping: 'Joe Consumer',
  line1: 'Via della Rosa, 58',
  suburb: 'Montelupo Fiorentino',
  phoneShipping: '0400000000',
  totalAmount: '190'
}
